### ISSUE TITLE
今天申请加电报群怎么直接给我禁了啊？

### ISSUE THREAD

**Issue by hwraul** [hex-ci/smzdm_script#53]
今天看到脚本账号被踢下线了，想进群看看，结果申请了就直接给禁了啊？  大佬能解一下吗？

**Comment by hwraul** [comment]
可以看到了，是不让加了吗？

**Comment by jasonxu9999** [comment]
我也被禁了，可以解一下吗？

**Comment by jasonxu9999** [comment]
大佬，在哪给你私发一下用户名啊🤔
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2025年05月21日 12:42 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [hex-ci/smzdm_script] 今天申请加电报群怎么直接给我禁了啊？ (Issue #53) 
hex-ci left a comment (hex-ci/smzdm_script#53)
我也被禁了，可以解一下吗？
可能是机器人处理的封禁，你可以发下电报用户名，我稍晚点看下。
