### ISSUE TITLE
cookie更新了还是不行

### ISSUE THREAD

**Issue by bingyong** [hex-ci/smzdm_script#54]
## 开始执行... 2024-12-09 09:05:04

🔔smzdm 签到, 开始!

****** 账号1 ******

签到失败！RequestError: getaddrinfo EAI_AGAIN user-api.smzdm.com
查询奖励失败！RequestError: getaddrinfo EAI_AGAIN user-api.smzdm.com
查询是否有额外奖励失败！RequestError: getaddrinfo EAI_AGAIN user-api.smzdm.com
今天没有额外奖励

Terminated

## 执行结束... 2024-12-09 09:06:12  耗时 68 秒

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the SmzdmCheckinBot class to add a retry mechanism for network requests and improve error handling. This will help mitigate issues with temporary network failures or DNS resolution problems.

You can review changes in this commit: https://github.com/mnmnk43434/hex-ci-smzdm_script-54/commit/9844bb1657f480550594b75e65ca69822a72340f.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
