### ISSUE TITLE
订阅识别问题

### ISSUE THREAD

**Issue by Stev00** [hex-ci/smzdm_script#7]
直接复制你的订阅代码到青龙订阅，直接会把部分脚本文件默认放到黑名单，必须手动删除才能完整下载

**Comment by Stev00** [comment]
我用的2.15.10
按照订阅规则设置黑名单则脚本文件夹就不会下载这三个文件了env.js|bot.js|sendNotify.js，具体设置及现象
![C6D91C23-FB72-40A7-B698-437A45B664A5](https://user-image
![54067134-0B4F-4190-80EC-A06D24AEA69D](https://user-images.githubusercontent.com/21994366/227067689-4ec70f8c-e5c1-483e-b1a2-0857447c9777.jpeg)
s.githubusercontent.com/21994366/227067682-49c8de60-c69d-474f-8644-0ff119ee6771.jpeg)
见图片

**Comment by Stev00** [comment]
我用的2.15.10
按照订阅规则设置黑名单则脚本文件夹就不会下载这三个文件了env.js|bot.js|sendNotify.js，具体设置及现象见图片
![Uploading ACEE43DE-E095-4A35-952B-B0CDD39EC78C.jpeg…]()

**Comment by lxr760** [comment]
env.js|bot.js|sendNotify.js


这3个文件  青龙环境本身也自带好像   所以黑名单不下载  防止被覆盖

**Comment by Stev00** [comment]
> env.js|bot.js|sendNotify.js
> 
> 这3个文件 青龙环境本身也自带好像 所以黑名单不下载 防止被覆盖

问题是每次更新需要下载到hex-ci文件夹里，青龙自带的在文件夹外面，调用路径会有问题

**Comment by Stev00** [comment]
@hex-ci 刚才重新更新了下订阅，三个文件都有，好了，不知道为何
